services:
  event-logger:
    image: event-logger
    env_file:
      - ../environment/event-logger/.env
    networks:
      - temporal-network
    environment:
      - PORT=8181
  ai-memory:
    image: ai-memory
    env_file:
      - ../environment/ai-memory/.env
    depends_on:
      - event-logger
    networks:
      - temporal-network
    environment:
      - PORT=8182
  semantic-cache:
    image: semantic-cache
    env_file:
      - ../environment/semantic-cache/.env
    depends_on:
      - event-logger
    networks:
      - temporal-network
    environment:
      - PORT=8183
  
  data-loader:
    image: data-loader
    env_file:
      - ../environment/data-loader/.env
    depends_on:
      - event-logger
    networks:
      - temporal-network
    environment:
      - PORT=8184
  host:
    image: host
    env_file:
      - ../environment/host/.env
    depends_on:
      - event-logger
      - ai-memory
      - semantic-cache
      - data-loader
    networks:
      - temporal-network
    ports:
      - 7860:7860

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
    external: true